using System.Numerics;
using Lab2;
var rsa = new RSA();
Console.WriteLine($"p: {rsa.p}");
Console.WriteLine($"q: {rsa.q}");
Console.WriteLine($"N: {rsa.N}");
Console.WriteLine($"PublicKey (e, n): ({rsa.PublicKey.Item1}, {rsa.PublicKey.Item2})");
Console.WriteLine($"PrivateKey (d, n): ({rsa.PrivateKey.Item1}, {rsa.PrivateKey.Item2})");
string source = "ненавижу хабр свинью нерабочую подсунули";
Console.WriteLine($"Исходная строка: {source}");
Console.WriteLine($"Расшифрованная строка: {rsa.Decrypt(rsa.Encrypt(source))}");
Console.WriteLine(rsa.Decrypt(rsa.Encrypt(new BigInteger(-17712))));
Console.WriteLine(rsa.Decrypt(rsa.Encrypt(new BigInteger(15036))));
Console.WriteLine(rsa.Decrypt(rsa.Encrypt(new BigInteger(13009))));
Console.WriteLine(rsa.Decrypt(rsa.Encrypt(new BigInteger(27001))));
Console.WriteLine(rsa.Decrypt(rsa.Encrypt(new BigInteger(37))));
Console.WriteLine(rsa.Decrypt(rsa.Encrypt(new BigInteger(1))));
